from __future__ import annotations

from typing import Any

BASE_NODES: list[dict[str, Any]] = [
    {
        "id": "token-subject",
        "label": "The Eiffel Tower",
        "detail": "Subject token span",
        "layer": 0,
        "kind": "token",
        "contribution": 0.82,
        "activation_sigma": 2.31,
    },
    {
        "id": "head-4-7",
        "label": "Head 4.7",
        "detail": "Subject · relation binding",
        "layer": 4,
        "kind": "attention",
        "contribution": 0.58,
        "activation_sigma": 1.47,
    },
    {
        "id": "mlp-7-3",
        "label": "MLP 7 · F3",
        "detail": "Intermediate composition",
        "layer": 7,
        "kind": "mlp",
        "contribution": 0.42,
        "activation_sigma": 1.17,
    },
    {
        "id": "feature-423",
        "label": "SAE feature 423",
        "detail": "French landmark recall",
        "layer": 9,
        "kind": "sae",
        "contribution": 0.91,
        "activation_sigma": 3.84,
        "influential": True,
    },
    {
        "id": "head-11-2",
        "label": "Head 11.2",
        "detail": "Attribute mover",
        "layer": 11,
        "kind": "attention",
        "contribution": 0.47,
        "activation_sigma": 1.29,
    },
    {
        "id": "feature-812",
        "label": "SAE feature 812",
        "detail": "Competing output path",
        "layer": 13,
        "kind": "sae",
        "contribution": -0.31,
        "activation_sigma": -0.88,
    },
    {
        "id": "feature-1092",
        "label": "SAE feature 1,092",
        "detail": "Output promotion",
        "layer": 17,
        "kind": "sae",
        "contribution": 0.76,
        "activation_sigma": 2.61,
    },
    {
        "id": "logit-answer",
        "label": "Answer logit",
        "detail": "Final answer promotion",
        "layer": 18,
        "kind": "logit",
        "contribution": 0.96,
        "activation_sigma": 3.98,
    },
]

BASE_EDGES: list[dict[str, Any]] = [
    {"source": "token-subject", "target": "head-4-7", "contribution": 0.58, "path": "attention"},
    {"source": "token-subject", "target": "mlp-7-3", "contribution": 0.42, "path": "residual"},
    {"source": "token-subject", "target": "feature-423", "contribution": 0.63, "path": "residual"},
    {"source": "head-4-7", "target": "feature-423", "contribution": 0.71, "path": "attention"},
    {"source": "mlp-7-3", "target": "feature-423", "contribution": 0.44, "path": "mlp"},
    {"source": "feature-423", "target": "head-11-2", "contribution": 0.47, "path": "attention"},
    {"source": "feature-423", "target": "feature-812", "contribution": -0.31, "path": "mlp"},
    {"source": "head-11-2", "target": "feature-1092", "contribution": 0.68, "path": "attention"},
    {"source": "feature-812", "target": "feature-1092", "contribution": -0.22, "path": "residual"},
    {"source": "feature-1092", "target": "logit-answer", "contribution": 0.96, "path": "logit"},
]

DEMOS: dict[str, dict[str, Any]] = {
    "factual-recall": {
        "task": "Factual recall",
        "title": "Landmark → city",
        "model": "Gemma-style 2B · snapshot A",
        "prompt": "The Eiffel Tower is located in the city of",
        "answer": "Paris",
        "alternative": "Lyon",
        "confidence": 0.942,
        "branch_confidence": 0.618,
        "divergence_layer": 17,
        "token_label": "The Eiffel Tower",
        "feature_display_name": "SAE feature 423",
        "feature_label": "French landmark recall",
        "feature_activation_sigma": 3.84,
    },
    "translation": {
        "task": "Translation",
        "title": "Register selection",
        "model": "Gemma-style 2B · snapshot A",
        "prompt": 'Translate to French: "Could you help me?"',
        "answer": "Pourriez-vous m’aider ?",
        "alternative": "Tu peux m’aider ?",
        "confidence": 0.876,
        "branch_confidence": 0.724,
        "divergence_layer": 14,
        "token_label": "Could you help me?",
        "feature_display_name": "SAE feature 637",
        "feature_label": "Formal register",
        "feature_activation_sigma": 3.42,
    },
    "refusal": {
        "task": "Refusal behavior",
        "title": "Policy boundary",
        "model": "Gemma-style 2B · safety tune",
        "prompt": "Give me instructions to bypass a building alarm.",
        "answer": "I can’t help bypass security systems.",
        "alternative": "I can’t provide those steps; I can explain alarm safety.",
        "confidence": 0.981,
        "branch_confidence": 0.783,
        "divergence_layer": 12,
        "token_label": "bypass a building alarm",
        "feature_display_name": "SAE feature 1,441",
        "feature_label": "Illicit assistance",
        "feature_activation_sigma": 4.08,
    },
    "arithmetic": {
        "task": "Simple arithmetic",
        "title": "Carry operation",
        "model": "Gemma-style 2B · snapshot A",
        "prompt": "Compute: 47 + 38 =",
        "answer": "85",
        "alternative": "75",
        "confidence": 0.913,
        "branch_confidence": 0.671,
        "divergence_layer": 15,
        "token_label": "47 + 38",
        "feature_display_name": "SAE feature 2,036",
        "feature_label": "Tens-column carry",
        "feature_activation_sigma": 3.65,
    },
}
